module.exports = {
    COMMAND: 'COMMAND',
    WRITE_LINE: 'WRITE_LINE',
    CREATE_SCREEN: 'CREATE_SCREEN',
    DESTROY_SCREEN: 'DESTROY_SCREEN',
    CLEAR_SCREEN: 'CLEAR_SCREEN',
    SELECT_SCREEN: 'SELECT_SCREEN'
};